In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
Ans:
    Yes, there is a difference in the data types of the variables list_ and array_list.

list_ is a Python list, which can hold elements of different data types, such as integers, strings, or even other objects. In
this case, the elements of list_ are strings.

array_list is a NumPy array, created using the np.array() function. NumPy arrays are homogeneous, meaning they can only hold
elements of the same data type. In this case, since the elements of list_ are strings, the elements of array_list will also be 
converted to strings.

To print the data types of both variables, you can use the type() function in Python. Here's the code to do that:

python
Copy code
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
When you run this code, it will output:

python
Copy code
Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>
As you can see, the data type of list_ is list, and the data type of array_list is numpy.ndarray.

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
Ans:
    To print the data type of each element in both list_ and array_list, you can use a loop to iterate over the elements and
    apply the type() function to each element. Here's the code:

python
Copy code
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print()

# Print data types of elements in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))
When you run this code, it will output:

arduino
Copy code
Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
As you can see, the elements in list_ are of type str, and the elements in array_list are of type numpy.str_, which is a 
specific string data type used by NumPy arrays.

In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Ans:
    Yes, there will be a difference in the data types of the elements present in list_ and array_list after the following 
    change:

array_list = np.array(object=list_, dtype=int)
In this case, the dtype=int argument is specified when creating the NumPy array array_list, which indicates that the elements
should be converted to the integer data type.

To print the data types of each element in both list_ and array_list, you can use a loop to iterate over the elements and apply
the type() function to each element. Here's the updated code:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print()

# Print data types of elements in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))
When you run this code, it will output:
    
Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
As you can see, the elements in list_ are still of type str, but the elements in array_list have been converted to the numpy.
int64 data type, which is the specified integer data type in this case.

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
Ans:
    To find the characteristics of the variable num_array, such as its shape and size, you can use the following code:

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# Find the size of num_array
size = num_array.size
print("Size of num_array:", size)
When you run this code, it will output:

Shape of num_array: (2, 3)
Size of num_array: 6
The shape of num_array is (2, 3), indicating that it has 2 rows and 3 columns. The size of num_array is 6, which represents the
total number of elements in the array.

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
Ans:
    To create a NumPy array of a 3x3 matrix containing zeros only, you can use the np.zeros() function. Here's the code:

python code
import numpy as np

zero_array = np.zeros((3, 3))

print(zero_array)
When you run this code, it will output:
    
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
The np.zeros() function takes the shape of the desired array as an argument. In this case, we pass (3, 3) to create a 3x3
matrix. Each element in the resulting array is initialized to 0.0 by default.

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
Ans:
    To create an identity matrix of shape (5, 5) using NumPy, you can use the np.eye() function. Here's the code:

python code
import numpy as np

identity_matrix = np.eye(5)

print(identity_matrix)
When you run this code, it will output:

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
The np.eye() function creates a square identity matrix with the specified shape. In this case, we pass 5 to create a 5x5 
identity matrix. The elements along the main diagonal are 1, and all other elements are 0.